name: smm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.0.5
  firebase_core: ^3.5.0
  provider: ^6.1.2
  cloud_firestore: ^5.4.2
  flick_video_player: ^0.9.0
  just_audio: ^0.9.40
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  file_picker: ^8.1.2
  uuid: ^4.5.0
  video_player: ^2.9.1
  story_maker: ^1.0.5
  share_plus: ^10.0.2
  fraction: ^5.0.3
  video_editor: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  visibility_detector: ^0.4.0+2
  image_picker: ^1.1.2
  pinput: ^5.0.0
  google_sign_in: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/1024.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/